In [38]:
#imports
import os
import psycopg2
import pandas as pd
import numpy as np
import torch
import pickle
import matplotlib.pyplot as plt
from dotenv import load_dotenv
from sqlalchemy import create_engine
from torch import nn
from torch.utils.data import Dataset, DataLoader, Subset
from torch.optim import Adam
from sklearn.svm  import LinearSVC
from sklearn.naive_bayes  import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from tqdm import tqdm
from scipy import stats

#loads global variables

load_dotenv()
    
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)


all_champions = np.array(['Aatrox', 'Ahri', 'Akali', 'Akshan', 'Alistar', 'Amumu', 'Anivia',
                    'Annie', 'Aphelios', 'Ashe', 'AurelionSol', 'Azir', 'Bard',
                    'Belveth', 'Blitzcrank', 'Brand', 'Braum', 'Briar', 'Caitlyn',
                    'Camille', 'Cassiopeia', 'Chogath', 'Corki', 'Darius', 'Diana',
                    'DrMundo', 'Draven', 'Ekko', 'Elise', 'Evelynn', 'Ezreal',
                    'FiddleSticks', 'Fiora', 'Fizz', 'Galio', 'Gangplank', 'Garen',
                    'Gnar', 'Gragas', 'Graves', 'Gwen', 'Hecarim', 'Heimerdinger',
                    'Hwei', 'Illaoi', 'Irelia', 'Ivern', 'Janna', 'JarvanIV', 'Jax',
                    'Jayce', 'Jhin', 'Jinx', 'KSante', 'Kaisa', 'Kalista', 'Karma',
                    'Karthus', 'Kassadin', 'Katarina', 'Kayle', 'Kayn', 'Kennen',
                    'Khazix', 'Kindred', 'Kled', 'KogMaw', 'Leblanc', 'LeeSin',
                    'Leona', 'Lillia', 'Lissandra', 'Lucian', 'Lulu', 'Lux',
                    'Malphite', 'Malzahar', 'Maokai', 'MasterYi', 'Milio',
                    'MissFortune', 'MonkeyKing', 'Mordekaiser', 'Morgana', 'Naafiri',
                    'Nami', 'Nasus', 'Nautilus', 'Neeko', 'Nidalee', 'Nilah',
                    'Nocturne', 'Nunu', 'Olaf', 'Orianna', 'Ornn', 'Pantheon', 'Poppy',
                    'Pyke', 'Qiyana', 'Quinn', 'Rakan', 'Rammus', 'RekSai', 'Rell',
                    'Renata', 'Renekton', 'Rengar', 'Riven', 'Rumble', 'Ryze',
                    'Samira', 'Sejuani', 'Senna', 'Seraphine', 'Sett', 'Shaco', 'Shen',
                    'Shyvana', 'Singed', 'Sion', 'Sivir', 'Skarner', 'Smolder', 'Sona',
                    'Soraka', 'Swain', 'Sylas', 'Syndra', 'TahmKench', 'Taliyah',
                    'Talon', 'Taric', 'Teemo', 'Thresh', 'Tristana', 'Trundle',
                    'Tryndamere', 'TwistedFate', 'Twitch', 'Udyr', 'Urgot', 'Varus',
                    'Vayne', 'Veigar', 'Velkoz', 'Vex', 'Vi', 'Viego', 'Viktor',
                    'Vladimir', 'Volibear', 'Warwick', 'Xayah', 'Xerath', 'XinZhao',
                    'Yasuo', 'Yone', 'Yorick', 'Yuumi', 'Zac', 'Zed', 'Zeri', 'Ziggs',
                    'Zilean', 'Zoe', 'Zyra'])

cuda:0


In [39]:
def get_csv(region='NA1',game_mode='ARAM',patch='14.13'):
    #gets data collected into a csv

    #if using sqlalchemy
    # engine_name = f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
    conn = psycopg2.connect(
        database = os.getenv('DB_NAME'),
        host = os.getenv('DB_HOST'),
        user = os.getenv('DB_USER'),
        password = os.getenv('DB_PASSWORD'),
        port = os.getenv('5432')
    )

    os.makedirs('MatchData', exist_ok=True)
    csv_path = f'MatchData/{region}_{game_mode}_{patch}.csv'

    cursor = conn.cursor()
    patch = patch+'%'

    query_sql = """SELECT * 
    FROM match_data 
    WHERE region = %s 
    AND game_mode = %s 
    AND patch LIKE %s"""

    query = cursor.mogrify(query_sql,(region, game_mode,patch))
    query = query.decode('utf-8')

    try:
        if os.path.exists(csv_path):
            print("Csv found")
        else:
            with open(csv_path,'w') as f:
                cursor.copy_expert("COPY ({}) TO STDOUT WITH CSV HEADER".format(query),f)
            print("Copy to csv successful")

    except (Exception, psycopg2.DatabaseError) as error:
        print(error)


In [40]:
def get_data(region='NA1',game_mode='ARAM',elo='ANY',version='14.13'):
    #initiates sql engine and uses it to get data given user settings and returns it as a dataframe
    engine_name = f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
    engine = create_engine(engine_name)
    
    version = version+'%'
    elo = elo+'%'

    if(elo == 'ANY%'):
        query_sql = """SELECT * 
        FROM match_data 
        WHERE region = %s 
        AND game_mode = %s 
        AND version LIKE %s"""
        params = (region,game_mode,version)
        
    else:
        query_sql = """SELECT * 
        FROM match_data 
        WHERE region = %s 
        AND game_mode = %s 
        AND elo LIKE %s
        AND version LIKE %s"""
        params = (region, game_mode, elo, version)

    df = pd.read_sql_query(query_sql,con=engine,params=params)
    return df

In [41]:
def verify_data(df = None):
    #any rows that are corrupted, either through an error in data write or read, are dropped
    df = df.dropna()
    
    blue_team = ['blue_one','blue_two','blue_three','blue_four', 'blue_five']
    red_team = ['red_one', 'red_two', 'red_three', 'red_four', 'red_five']
    
    blue_team_encoded = np.zeros((len(df),len(all_champions)))
    blue_team_columns = [f"blue_{champ}" for champ in all_champions]
    red_team_encoded = np.zeros((len(df),len(all_champions)))
    red_team_columns = [f"red_{champ}" for champ in all_champions]

    #encode the blue and red champions using bag of words 
    for idx,row in df.iterrows():
        for col in blue_team:
            champ = row[col]
            champ_index = np.where(all_champions == champ)[0]
            blue_team_encoded[idx][champ_index] = 1

        for col in red_team: 
            champ = row[col]
            champ_index = np.where(all_champions == champ)[0]
            red_team_encoded[idx][champ_index] = 1

    #convery  encoded data from array to dataframe and concatenate the blue and red team dataframes
    #also drop columns we will not be using
    blue_team_encoded = pd.DataFrame(blue_team_encoded,columns=blue_team_columns)
    red_team_encoded = pd.DataFrame(red_team_encoded, columns=red_team_columns)

    match_ids = df['match_id']

    df = df.drop(columns=['id','region','match_id','game_mode','elo','version'])
    df = df.drop(columns=blue_team)
    df = df.drop(columns=red_team)
    df = pd.concat([df,blue_team_encoded,red_team_encoded],axis=1)

    return df, match_ids

In [42]:
class DraftAnalysisNN(nn.Module):
    def __init__(self,input_size,output_size):
        super().__init__()
        self.conv1 = nn.Conv1d(input_size,16,1)
        self.conv2 = nn.Conv1d(16,32,1)
        self.fc1 = nn.Linear(167 * 32 * 1,64)
        self.fc2 = nn.Linear(64,output_size)
        self.act = nn.ReLU()
    
    def forward(self,input):
        logits = self.act(self.conv1(input))
        logits = self.act(self.conv2(logits))
        logits = logits.view(logits.size(0),-1)
        logits = self.fc1(logits)
        logits = self.fc2(logits)
        
        output = torch.softmax(logits,dim=1)
        return output

In [43]:
class MatchDataset(Dataset):
    def __init__(self,df):
        self.label = np.array(df.iloc[:,0])
        self.input =  np.array(df.iloc[:,1:df.shape[1]])
        self.data = df

    def __len__(self):
        return len(self.data)
    
    def __getitem__(self,idx):
        split = int((self.data.shape[1]-1)/2)
        blue_team = self.data.iloc[idx,1:split+1]
        red_team = self.data.iloc[idx,split+1:self.data.shape[1]]

        blue_team_tensor = torch.tensor(blue_team.values, dtype=torch.float32)
        red_team_tensor = torch.tensor(red_team.values, dtype=torch.float32)

        input = torch.stack((blue_team_tensor,red_team_tensor),dim=0).to(device)

        label = self.data.iloc[idx,0]
        label = torch.tensor(label, dtype=torch.long).to(device)
        return {
            'input': input,
            'label' : label
        }

In [44]:
def split_data(data,batch_size):
    #split the data of the dataset and array (dataset for nn, array for scipy)
    train_indices, test_indices = train_test_split(range(len(data)), test_size=0.2, random_state=42, shuffle=True)
    train_dataset = Subset(data, train_indices)
    test_dataset = Subset(data, test_indices)
    train_loader = DataLoader(train_dataset, batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=1, shuffle=True)

    train_inputs, test_inputs, train_labels, test_labels = train_test_split(data.input, data.label, test_size=0.2, random_state=42, shuffle=True)

    return train_loader,test_loader, train_inputs, test_inputs, train_labels, test_labels

In [45]:
def train_models(train_loader, train_inputs, train_labels, num_epochs, paths):
    #training loop
    SVC_model = LinearSVC(dual = 'auto')
    GNB_model = GaussianNB()
    channels = next(iter(train_loader))['input'].shape[1]
    NN_model = DraftAnalysisNN(channels,channels).to(device)
    
    SVC_model.fit(train_inputs,train_labels)
    GNB_model.fit(train_inputs,train_labels)

    criterion = nn.CrossEntropyLoss()
    optimizer = Adam(NN_model.parameters(),lr=1e-5)

    print(f'Starting training of {num_epochs} epochs')
    NN_model.zero_grad()
    NN_model.train()

    train_losses = []
    for epoch in range(num_epochs):
        train_loss = 0
        for batch in tqdm(train_loader):
            input = batch['input']
            label = batch['label']

            optimizer.zero_grad()
            output = NN_model(input)
            loss = criterion(output,label)
            train_loss += loss.item()

            loss.backward()
            optimizer.step()
        train_loss /= len(train_loader)
        train_losses.append(train_loss)

        print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {train_loss:.4f}')

    #save model
    print(f'Saving models')
    with open(paths['SVC'], 'wb') as file:
        pickle.dump(SVC_model,file)
    
    with open(paths['GNB'],'wb') as file:
        pickle.dump(GNB_model, file)
    
    torch.save(NN_model.state_dict(),paths['NN'])

    return SVC_model, GNB_model, NN_model


In [46]:
def test_models(SVC_model,GNB_model, NN_model, test_loader, test_inputs, test_labels):
    #test models
    SVC_predictions = SVC_model.predict(test_inputs)
    GNB_predictions = GNB_model.predict(test_inputs)
    
    print('Testing Models')
    NN_model.eval()
    NN_predictions = []
    labels = []
    voting_predictions = []
    with torch.no_grad():
        for batch in tqdm(test_loader):
            input = batch['input']
            label = batch['label'].cpu().numpy()

            output = NN_model(input)
            prediction = torch.argmax(output, dim=1)
            print(output)
            NN_pred = prediction.cpu().numpy()

            NN_predictions.extend(NN_pred)
            labels.extend(label)

            sklearn_input = input.flatten().cpu().numpy().reshape((input.shape[0], -1))
            SVC_pred = SVC_model.predict(sklearn_input)
            GNB_pred = GNB_model.predict(sklearn_input)

            #voting implementation
            combined_preds = np.stack([NN_pred, SVC_pred, GNB_pred], axis=0)
            voting_result = stats.mode(combined_preds)
            voting_predictions.extend(voting_result[0])
    
    SVC_acc = accuracy_score(SVC_predictions, test_labels)
    GNB_acc = accuracy_score(GNB_predictions, test_labels)
    NN_acc = accuracy_score(NN_predictions,labels)
    voting_acc = accuracy_score(voting_predictions, labels)
    
    print(f'SVC Accuracy: {SVC_acc:.2f}')
    print(f'GNB Accuracy: {GNB_acc:.2f}')
    print(f'NN Accuracy: {NN_acc:.2f}')
    print(f'Voting Accuracy: {voting_acc:.2f}')

    

In [47]:
def predict(SVC_model,GNB_model,NN_model, blue_team, red_team):
    #encode the blue_team and red_team inputs
    blue_team_encoded = np.zeros(len(all_champions))
    red_team_encoded = np.zeros(len(all_champions))

    for champ in blue_team:
        champ_index = np.where(all_champions == champ)[0]
        if champ_index.size == 0:
            raise ValueError(f"Champion '{champ}' not found in list.")
        blue_team_encoded[champ_index] = 1

    for champ in red_team:
        champ_index = np.where(all_champions == champ)[0]
        if champ_index.size == 0:
            raise ValueError(f"Champion '{champ}' not found in list.")
        red_team_encoded[champ_index] = 1

    #create sklearn input as a numpy array and pytorch nn input as a tensor
    sklearn_input = np.concatenate((blue_team_encoded,red_team_encoded),axis=None).reshape(1,-1)
    SVC_pred = SVC_model.predict(sklearn_input)
    GNB_pred = GNB_model.predict(sklearn_input)
    
    nn_input = torch.vstack((torch.tensor(red_team_encoded),torch.tensor(blue_team_encoded))).float().unsqueeze(0).to(device)
    output = NN_model(nn_input)
    prediction = torch.argmax(output, dim=1)
    NN_pred = prediction.cpu().numpy()
    
    #voting implementation
    combined_preds = np.stack([NN_pred, SVC_pred, GNB_pred], axis=0)
    voting_result = stats.mode(combined_preds)[0]

    #print results
    if voting_result == 0:
        winner = 'Blue Team'
    else:
        winner = 'Red Team'
    
    winner = 'Blue Team' if voting_result == 0 else 'Red Team'
    
    print(f'Predicted winner is {winner}')
    print(f'SVC model predicted {"Blue Team" if SVC_pred[0] == 0 else "Red Team"}')
    print(f'GNB model predicted {"Blue Team" if GNB_pred[0] == 0 else "Red Team"}')
    print(f'NN model predicted {"Blue Team" if NN_pred[0] == 0 else "Red Team"} with a {output[0][0]*100 if NN_pred[0] == 0 else output[0][1]*100:.2f}% chance')

    return sklearn_input



In [48]:
def get_similar_game(encoded_data, threshold, inputs, labels, match_ids):
    matching_elements = (inputs == 1) & (encoded_data == 1)
    match_counts = np.sum(matching_elements, axis=1)
    matching_ids = match_ids[match_counts >= threshold]
    matching_labels = labels[match_counts >= threshold]
    
    if matching_ids.empty:
        print(f'Found no games with {threshold} or more similar characters')
    else:
        for idx, id in enumerate(matching_ids):
            region, id_num = id.split('_')
            if region == 'NA1':
                region = 'NA'
            region = region.lower()
            winner = 'Blue Team' if matching_labels[idx] else 'Red Team'
            print(f'https://www.leagueofgraphs.com/match/{region}/{id_num}, {winner} won')


In [49]:
def main(region, game_mode, elo, version, batch_size, num_epochs, override, blue_team, red_team, threshold):
    #error testing
    if len(blue_team) != 5 or len(red_team) != 5:
        raise ValueError("Both teams must have exactly 5 champions. "
                         f"Current sizes - Blue team: {len(blue_team)}, Red team: {len(red_team)}")
    if len(blue_team) != len(set(blue_team)):
        raise ValueError("Duplicate champions found in blue team")
    if len(red_team) != len(set(red_team)):
        raise ValueError("Duplicate champions found in red team")
    
    #label paths
    prefix = f'Models/{region}_{game_mode}_{elo}_{version}_'
    paths = {
        'SVC' : prefix+'svc_model.pkl',
        'GNB' : prefix+'gnb_model.pkl',
        'NN' : prefix+'nn_model.pth'
    }

    #gets data
    df = get_data(region,game_mode,elo,version)
    df, match_ids = verify_data(df)
    data = MatchDataset(df) 
    print(f'Found {len(match_ids)} games with given settings')

    #train/test models if it does not exist. Otherwise load models and predict whether blue or red team will win based on the given champions
    if(override or not all(os.path.exists(path) for path in paths.values())):
        print('Override is true or model(s) missing, training/testing models')
        train_loader,test_loader, train_inputs, test_inputs, train_labels, test_labels = split_data(data,batch_size)
        SVC_model, GNB_model, NN_model = train_models(train_loader,train_inputs, train_labels, num_epochs, paths)
        test_models(SVC_model,GNB_model, NN_model, test_loader, test_inputs, test_labels)
    else:
        print('Models exist, loading models')
        with open(paths['SVC'],'rb') as file:
            SVC_model = pickle.load(file)
    
        with open(paths['GNB'],'rb') as file:
            GNB_model = pickle.load(file)

        NN_model = DraftAnalysisNN(2,2).to(device)
        NN_model.load_state_dict(torch.load(paths['NN']))

    #prediction
    encoded_data = predict(SVC_model,GNB_model,NN_model, blue_team, red_team)
    #get old games based on threshold value, if threshold = 5, get all games where 5 champions match up to our 5 champions (on same team)
    get_similar_game(encoded_data[0],threshold,data.input,data.label, match_ids)
    
blue_team = ['Naafiri','Braum','Kayn','Kled','Smolder']
red_team = ['Akshan','Viego','Leona','Camille','Aphelios']
main('NA1','ARAM','ANY','14.13', batch_size=1, num_epochs=10, override=True, blue_team=blue_team, red_team=red_team, threshold=5 )

Found 5072 games with given settings
Override is true or model(s) missing, training/testing models
Starting training of 10 epochs


100%|██████████| 4057/4057 [00:12<00:00, 319.22it/s]


Epoch [1/10], Loss: 0.6939


100%|██████████| 4057/4057 [00:11<00:00, 341.42it/s]


Epoch [2/10], Loss: 0.6920


100%|██████████| 4057/4057 [00:12<00:00, 327.76it/s]


Epoch [3/10], Loss: 0.6913


100%|██████████| 4057/4057 [00:12<00:00, 320.38it/s]


Epoch [4/10], Loss: 0.6912


100%|██████████| 4057/4057 [00:11<00:00, 341.05it/s]


Epoch [5/10], Loss: 0.6899


100%|██████████| 4057/4057 [00:12<00:00, 336.66it/s]


Epoch [6/10], Loss: 0.6893


100%|██████████| 4057/4057 [00:11<00:00, 340.30it/s]


Epoch [7/10], Loss: 0.6874


100%|██████████| 4057/4057 [00:12<00:00, 338.00it/s]


Epoch [8/10], Loss: 0.6859


100%|██████████| 4057/4057 [00:11<00:00, 341.81it/s]


Epoch [9/10], Loss: 0.6835


100%|██████████| 4057/4057 [00:11<00:00, 340.82it/s]


Epoch [10/10], Loss: 0.6819
Saving models
Testing Models


  3%|▎         | 30/1015 [00:00<00:08, 115.72it/s]

tensor([[0.5278, 0.4722]], device='cuda:0')
tensor([[0.5445, 0.4555]], device='cuda:0')
tensor([[0.3938, 0.6062]], device='cuda:0')
tensor([[0.4810, 0.5190]], device='cuda:0')
tensor([[0.5693, 0.4307]], device='cuda:0')
tensor([[0.6011, 0.3989]], device='cuda:0')
tensor([[0.5467, 0.4533]], device='cuda:0')
tensor([[0.4790, 0.5210]], device='cuda:0')
tensor([[0.5354, 0.4646]], device='cuda:0')
tensor([[0.6087, 0.3913]], device='cuda:0')
tensor([[0.4685, 0.5315]], device='cuda:0')
tensor([[0.6047, 0.3953]], device='cuda:0')
tensor([[0.5512, 0.4488]], device='cuda:0')
tensor([[0.6537, 0.3463]], device='cuda:0')
tensor([[0.5909, 0.4091]], device='cuda:0')
tensor([[0.5557, 0.4443]], device='cuda:0')
tensor([[0.5009, 0.4991]], device='cuda:0')
tensor([[0.5632, 0.4368]], device='cuda:0')
tensor([[0.5816, 0.4184]], device='cuda:0')
tensor([[0.4744, 0.5256]], device='cuda:0')
tensor([[0.4853, 0.5147]], device='cuda:0')
tensor([[0.5377, 0.4623]], device='cuda:0')
tensor([[0.4993, 0.5007]], devic

 11%|█         | 114/1015 [00:00<00:03, 228.35it/s]

tensor([[0.5298, 0.4702]], device='cuda:0')
tensor([[0.5681, 0.4319]], device='cuda:0')
tensor([[0.6224, 0.3776]], device='cuda:0')
tensor([[0.5412, 0.4588]], device='cuda:0')
tensor([[0.5450, 0.4550]], device='cuda:0')
tensor([[0.4735, 0.5265]], device='cuda:0')
tensor([[0.4951, 0.5049]], device='cuda:0')
tensor([[0.5535, 0.4465]], device='cuda:0')
tensor([[0.5784, 0.4216]], device='cuda:0')
tensor([[0.4890, 0.5110]], device='cuda:0')
tensor([[0.5113, 0.4887]], device='cuda:0')
tensor([[0.5171, 0.4829]], device='cuda:0')
tensor([[0.5144, 0.4856]], device='cuda:0')
tensor([[0.4660, 0.5340]], device='cuda:0')
tensor([[0.5047, 0.4953]], device='cuda:0')
tensor([[0.5230, 0.4770]], device='cuda:0')
tensor([[0.5571, 0.4429]], device='cuda:0')
tensor([[0.5600, 0.4400]], device='cuda:0')
tensor([[0.5323, 0.4677]], device='cuda:0')
tensor([[0.5146, 0.4854]], device='cuda:0')
tensor([[0.5163, 0.4837]], device='cuda:0')
tensor([[0.5243, 0.4757]], device='cuda:0')
tensor([[0.5613, 0.4387]], devic

 17%|█▋        | 172/1015 [00:00<00:03, 253.25it/s]

tensor([[0.5190, 0.4810]], device='cuda:0')
tensor([[0.5875, 0.4125]], device='cuda:0')
tensor([[0.5661, 0.4339]], device='cuda:0')
tensor([[0.5234, 0.4766]], device='cuda:0')
tensor([[0.5057, 0.4943]], device='cuda:0')
tensor([[0.5655, 0.4345]], device='cuda:0')
tensor([[0.5210, 0.4790]], device='cuda:0')
tensor([[0.4518, 0.5482]], device='cuda:0')
tensor([[0.5721, 0.4279]], device='cuda:0')
tensor([[0.5550, 0.4450]], device='cuda:0')
tensor([[0.4858, 0.5142]], device='cuda:0')
tensor([[0.4948, 0.5052]], device='cuda:0')
tensor([[0.6036, 0.3964]], device='cuda:0')
tensor([[0.5018, 0.4982]], device='cuda:0')
tensor([[0.4782, 0.5218]], device='cuda:0')
tensor([[0.4409, 0.5591]], device='cuda:0')
tensor([[0.5968, 0.4032]], device='cuda:0')
tensor([[0.5251, 0.4749]], device='cuda:0')
tensor([[0.5177, 0.4823]], device='cuda:0')
tensor([[0.4793, 0.5207]], device='cuda:0')
tensor([[0.4161, 0.5839]], device='cuda:0')
tensor([[0.5183, 0.4817]], device='cuda:0')
tensor([[0.4837, 0.5163]], devic

 20%|█▉        | 200/1015 [00:00<00:03, 259.74it/s]

tensor([[0.6033, 0.3967]], device='cuda:0')
tensor([[0.5129, 0.4871]], device='cuda:0')
tensor([[0.5217, 0.4783]], device='cuda:0')
tensor([[0.5281, 0.4719]], device='cuda:0')
tensor([[0.5758, 0.4242]], device='cuda:0')
tensor([[0.4796, 0.5204]], device='cuda:0')
tensor([[0.5292, 0.4708]], device='cuda:0')
tensor([[0.4976, 0.5024]], device='cuda:0')
tensor([[0.4482, 0.5518]], device='cuda:0')
tensor([[0.5193, 0.4807]], device='cuda:0')
tensor([[0.4824, 0.5176]], device='cuda:0')
tensor([[0.5422, 0.4578]], device='cuda:0')
tensor([[0.5583, 0.4417]], device='cuda:0')
tensor([[0.5867, 0.4133]], device='cuda:0')
tensor([[0.5372, 0.4628]], device='cuda:0')
tensor([[0.4453, 0.5547]], device='cuda:0')
tensor([[0.5890, 0.4110]], device='cuda:0')
tensor([[0.5573, 0.4427]], device='cuda:0')
tensor([[0.6006, 0.3994]], device='cuda:0')
tensor([[0.5374, 0.4626]], device='cuda:0')
tensor([[0.5389, 0.4611]], device='cuda:0')
tensor([[0.5945, 0.4055]], device='cuda:0')
tensor([[0.5509, 0.4491]], devic

 25%|██▌       | 255/1015 [00:01<00:02, 261.63it/s]

tensor([[0.5015, 0.4985]], device='cuda:0')
tensor([[0.5155, 0.4845]], device='cuda:0')
tensor([[0.5449, 0.4551]], device='cuda:0')
tensor([[0.5649, 0.4351]], device='cuda:0')
tensor([[0.5925, 0.4075]], device='cuda:0')
tensor([[0.5463, 0.4537]], device='cuda:0')
tensor([[0.5559, 0.4441]], device='cuda:0')
tensor([[0.5803, 0.4197]], device='cuda:0')
tensor([[0.5387, 0.4613]], device='cuda:0')
tensor([[0.5003, 0.4997]], device='cuda:0')
tensor([[0.5432, 0.4568]], device='cuda:0')
tensor([[0.4062, 0.5938]], device='cuda:0')
tensor([[0.4983, 0.5017]], device='cuda:0')
tensor([[0.5436, 0.4564]], device='cuda:0')
tensor([[0.5154, 0.4846]], device='cuda:0')
tensor([[0.5711, 0.4289]], device='cuda:0')
tensor([[0.5428, 0.4572]], device='cuda:0')
tensor([[0.5447, 0.4553]], device='cuda:0')
tensor([[0.5136, 0.4864]], device='cuda:0')
tensor([[0.5271, 0.4729]], device='cuda:0')
tensor([[0.5352, 0.4648]], device='cuda:0')
tensor([[0.4488, 0.5512]], device='cuda:0')
tensor([[0.5480, 0.4520]], devic

 33%|███▎      | 339/1015 [00:01<00:02, 267.84it/s]

tensor([[0.6466, 0.3534]], device='cuda:0')
tensor([[0.5595, 0.4405]], device='cuda:0')
tensor([[0.5619, 0.4381]], device='cuda:0')
tensor([[0.4607, 0.5393]], device='cuda:0')
tensor([[0.5882, 0.4118]], device='cuda:0')
tensor([[0.5953, 0.4047]], device='cuda:0')
tensor([[0.6132, 0.3868]], device='cuda:0')
tensor([[0.5503, 0.4497]], device='cuda:0')
tensor([[0.4969, 0.5031]], device='cuda:0')
tensor([[0.4853, 0.5147]], device='cuda:0')
tensor([[0.5498, 0.4502]], device='cuda:0')
tensor([[0.5763, 0.4237]], device='cuda:0')
tensor([[0.4771, 0.5229]], device='cuda:0')
tensor([[0.5673, 0.4327]], device='cuda:0')
tensor([[0.5174, 0.4826]], device='cuda:0')
tensor([[0.5143, 0.4857]], device='cuda:0')
tensor([[0.5095, 0.4905]], device='cuda:0')
tensor([[0.4723, 0.5277]], device='cuda:0')
tensor([[0.5106, 0.4894]], device='cuda:0')
tensor([[0.5641, 0.4359]], device='cuda:0')
tensor([[0.5435, 0.4565]], device='cuda:0')
tensor([[0.4959, 0.5041]], device='cuda:0')
tensor([[0.5348, 0.4652]], devic

 39%|███▉      | 394/1015 [00:01<00:02, 267.38it/s]

tensor([[0.5943, 0.4057]], device='cuda:0')
tensor([[0.4766, 0.5234]], device='cuda:0')
tensor([[0.5378, 0.4622]], device='cuda:0')
tensor([[0.6235, 0.3765]], device='cuda:0')
tensor([[0.5413, 0.4587]], device='cuda:0')
tensor([[0.5336, 0.4664]], device='cuda:0')
tensor([[0.4500, 0.5500]], device='cuda:0')
tensor([[0.5817, 0.4183]], device='cuda:0')
tensor([[0.5515, 0.4485]], device='cuda:0')
tensor([[0.4985, 0.5015]], device='cuda:0')
tensor([[0.4982, 0.5018]], device='cuda:0')
tensor([[0.5057, 0.4943]], device='cuda:0')
tensor([[0.6343, 0.3657]], device='cuda:0')
tensor([[0.5442, 0.4558]], device='cuda:0')
tensor([[0.6674, 0.3326]], device='cuda:0')
tensor([[0.6120, 0.3880]], device='cuda:0')
tensor([[0.5176, 0.4824]], device='cuda:0')
tensor([[0.5286, 0.4714]], device='cuda:0')
tensor([[0.5025, 0.4975]], device='cuda:0')
tensor([[0.5113, 0.4887]], device='cuda:0')
tensor([[0.6434, 0.3566]], device='cuda:0')
tensor([[0.6428, 0.3572]], device='cuda:0')
tensor([[0.5577, 0.4423]], devic

 41%|████▏     | 421/1015 [00:01<00:02, 266.77it/s]

tensor([[0.5445, 0.4555]], device='cuda:0')
tensor([[0.6100, 0.3900]], device='cuda:0')
tensor([[0.5490, 0.4510]], device='cuda:0')
tensor([[0.5835, 0.4165]], device='cuda:0')
tensor([[0.4916, 0.5084]], device='cuda:0')
tensor([[0.5112, 0.4888]], device='cuda:0')
tensor([[0.5048, 0.4952]], device='cuda:0')
tensor([[0.5275, 0.4725]], device='cuda:0')
tensor([[0.6325, 0.3675]], device='cuda:0')
tensor([[0.5720, 0.4280]], device='cuda:0')
tensor([[0.4976, 0.5024]], device='cuda:0')
tensor([[0.5497, 0.4503]], device='cuda:0')
tensor([[0.5151, 0.4849]], device='cuda:0')
tensor([[0.5909, 0.4091]], device='cuda:0')
tensor([[0.5835, 0.4165]], device='cuda:0')
tensor([[0.5628, 0.4372]], device='cuda:0')
tensor([[0.5467, 0.4533]], device='cuda:0')
tensor([[0.5104, 0.4896]], device='cuda:0')
tensor([[0.5860, 0.4140]], device='cuda:0')
tensor([[0.5291, 0.4709]], device='cuda:0')
tensor([[0.5462, 0.4538]], device='cuda:0')
tensor([[0.5486, 0.4514]], device='cuda:0')
tensor([[0.5399, 0.4601]], devic

 47%|████▋     | 475/1015 [00:01<00:02, 264.23it/s]

tensor([[0.4861, 0.5139]], device='cuda:0')
tensor([[0.4467, 0.5533]], device='cuda:0')
tensor([[0.5400, 0.4600]], device='cuda:0')
tensor([[0.5431, 0.4569]], device='cuda:0')
tensor([[0.4900, 0.5100]], device='cuda:0')
tensor([[0.5783, 0.4217]], device='cuda:0')
tensor([[0.5220, 0.4780]], device='cuda:0')
tensor([[0.6001, 0.3999]], device='cuda:0')
tensor([[0.5366, 0.4634]], device='cuda:0')
tensor([[0.6302, 0.3698]], device='cuda:0')
tensor([[0.4949, 0.5051]], device='cuda:0')
tensor([[0.5283, 0.4717]], device='cuda:0')
tensor([[0.5066, 0.4934]], device='cuda:0')
tensor([[0.5419, 0.4581]], device='cuda:0')
tensor([[0.5036, 0.4964]], device='cuda:0')
tensor([[0.5723, 0.4277]], device='cuda:0')
tensor([[0.5125, 0.4875]], device='cuda:0')
tensor([[0.5050, 0.4950]], device='cuda:0')
tensor([[0.4739, 0.5261]], device='cuda:0')
tensor([[0.5252, 0.4748]], device='cuda:0')
tensor([[0.5108, 0.4892]], device='cuda:0')
tensor([[0.5433, 0.4567]], device='cuda:0')
tensor([[0.5200, 0.4800]], devic

 52%|█████▏    | 529/1015 [00:02<00:01, 258.27it/s]

tensor([[0.6277, 0.3723]], device='cuda:0')
tensor([[0.5949, 0.4051]], device='cuda:0')
tensor([[0.5958, 0.4042]], device='cuda:0')
tensor([[0.4778, 0.5222]], device='cuda:0')
tensor([[0.5916, 0.4084]], device='cuda:0')
tensor([[0.5858, 0.4142]], device='cuda:0')
tensor([[0.5098, 0.4902]], device='cuda:0')
tensor([[0.5413, 0.4587]], device='cuda:0')
tensor([[0.5567, 0.4433]], device='cuda:0')
tensor([[0.5348, 0.4652]], device='cuda:0')
tensor([[0.4838, 0.5162]], device='cuda:0')
tensor([[0.5238, 0.4762]], device='cuda:0')
tensor([[0.5778, 0.4222]], device='cuda:0')
tensor([[0.5492, 0.4508]], device='cuda:0')
tensor([[0.5046, 0.4954]], device='cuda:0')
tensor([[0.4825, 0.5175]], device='cuda:0')
tensor([[0.4963, 0.5037]], device='cuda:0')
tensor([[0.5229, 0.4771]], device='cuda:0')
tensor([[0.5259, 0.4741]], device='cuda:0')
tensor([[0.5154, 0.4846]], device='cuda:0')
tensor([[0.5647, 0.4353]], device='cuda:0')
tensor([[0.4573, 0.5427]], device='cuda:0')
tensor([[0.5450, 0.4550]], devic

 57%|█████▋    | 582/1015 [00:02<00:01, 258.04it/s]

tensor([[0.5443, 0.4557]], device='cuda:0')
tensor([[0.5710, 0.4290]], device='cuda:0')
tensor([[0.5815, 0.4185]], device='cuda:0')
tensor([[0.4993, 0.5007]], device='cuda:0')
tensor([[0.5694, 0.4306]], device='cuda:0')
tensor([[0.5804, 0.4196]], device='cuda:0')
tensor([[0.5446, 0.4554]], device='cuda:0')
tensor([[0.5256, 0.4744]], device='cuda:0')
tensor([[0.4515, 0.5485]], device='cuda:0')
tensor([[0.5602, 0.4398]], device='cuda:0')
tensor([[0.6054, 0.3946]], device='cuda:0')
tensor([[0.5307, 0.4693]], device='cuda:0')
tensor([[0.5374, 0.4626]], device='cuda:0')
tensor([[0.5756, 0.4244]], device='cuda:0')
tensor([[0.5866, 0.4134]], device='cuda:0')
tensor([[0.5120, 0.4880]], device='cuda:0')
tensor([[0.5149, 0.4851]], device='cuda:0')
tensor([[0.4843, 0.5157]], device='cuda:0')
tensor([[0.5433, 0.4567]], device='cuda:0')
tensor([[0.5714, 0.4286]], device='cuda:0')
tensor([[0.6323, 0.3677]], device='cuda:0')
tensor([[0.5574, 0.4426]], device='cuda:0')
tensor([[0.5854, 0.4146]], devic

 62%|██████▏   | 634/1015 [00:02<00:01, 250.27it/s]

tensor([[0.5306, 0.4694]], device='cuda:0')
tensor([[0.4943, 0.5057]], device='cuda:0')
tensor([[0.5788, 0.4212]], device='cuda:0')
tensor([[0.5448, 0.4552]], device='cuda:0')
tensor([[0.5584, 0.4416]], device='cuda:0')
tensor([[0.5309, 0.4691]], device='cuda:0')
tensor([[0.5758, 0.4242]], device='cuda:0')
tensor([[0.4666, 0.5334]], device='cuda:0')
tensor([[0.5173, 0.4827]], device='cuda:0')
tensor([[0.4683, 0.5317]], device='cuda:0')
tensor([[0.4953, 0.5047]], device='cuda:0')
tensor([[0.5116, 0.4884]], device='cuda:0')
tensor([[0.4811, 0.5189]], device='cuda:0')
tensor([[0.6152, 0.3848]], device='cuda:0')
tensor([[0.5319, 0.4681]], device='cuda:0')
tensor([[0.4182, 0.5818]], device='cuda:0')
tensor([[0.5239, 0.4761]], device='cuda:0')
tensor([[0.6076, 0.3924]], device='cuda:0')
tensor([[0.4906, 0.5094]], device='cuda:0')
tensor([[0.5173, 0.4827]], device='cuda:0')
tensor([[0.5135, 0.4865]], device='cuda:0')
tensor([[0.5637, 0.4363]], device='cuda:0')
tensor([[0.5292, 0.4708]], devic

 67%|██████▋   | 685/1015 [00:02<00:01, 236.16it/s]

tensor([[0.4824, 0.5176]], device='cuda:0')
tensor([[0.4630, 0.5370]], device='cuda:0')
tensor([[0.6269, 0.3731]], device='cuda:0')
tensor([[0.5359, 0.4641]], device='cuda:0')
tensor([[0.5112, 0.4888]], device='cuda:0')
tensor([[0.5494, 0.4506]], device='cuda:0')
tensor([[0.6695, 0.3305]], device='cuda:0')
tensor([[0.5407, 0.4593]], device='cuda:0')
tensor([[0.5858, 0.4142]], device='cuda:0')
tensor([[0.5185, 0.4815]], device='cuda:0')
tensor([[0.5839, 0.4161]], device='cuda:0')
tensor([[0.5582, 0.4418]], device='cuda:0')
tensor([[0.5574, 0.4426]], device='cuda:0')
tensor([[0.5922, 0.4078]], device='cuda:0')
tensor([[0.5736, 0.4264]], device='cuda:0')
tensor([[0.5562, 0.4438]], device='cuda:0')
tensor([[0.5159, 0.4841]], device='cuda:0')
tensor([[0.5200, 0.4800]], device='cuda:0')
tensor([[0.5330, 0.4670]], device='cuda:0')
tensor([[0.5147, 0.4853]], device='cuda:0')
tensor([[0.5727, 0.4273]], device='cuda:0')
tensor([[0.5732, 0.4268]], device='cuda:0')
tensor([[0.6232, 0.3768]], devic

 73%|███████▎  | 736/1015 [00:03<00:01, 240.48it/s]

tensor([[0.5532, 0.4468]], device='cuda:0')
tensor([[0.6545, 0.3455]], device='cuda:0')
tensor([[0.5698, 0.4302]], device='cuda:0')
tensor([[0.5303, 0.4697]], device='cuda:0')
tensor([[0.5324, 0.4676]], device='cuda:0')
tensor([[0.5946, 0.4054]], device='cuda:0')
tensor([[0.6091, 0.3909]], device='cuda:0')
tensor([[0.5749, 0.4251]], device='cuda:0')
tensor([[0.5753, 0.4247]], device='cuda:0')
tensor([[0.5532, 0.4468]], device='cuda:0')
tensor([[0.4903, 0.5097]], device='cuda:0')
tensor([[0.5529, 0.4471]], device='cuda:0')
tensor([[0.5255, 0.4745]], device='cuda:0')
tensor([[0.5096, 0.4904]], device='cuda:0')
tensor([[0.4826, 0.5174]], device='cuda:0')
tensor([[0.5288, 0.4712]], device='cuda:0')
tensor([[0.6382, 0.3618]], device='cuda:0')
tensor([[0.4894, 0.5106]], device='cuda:0')
tensor([[0.5039, 0.4961]], device='cuda:0')
tensor([[0.5290, 0.4710]], device='cuda:0')
tensor([[0.6344, 0.3656]], device='cuda:0')
tensor([[0.5966, 0.4034]], device='cuda:0')
tensor([[0.4735, 0.5265]], devic

 78%|███████▊  | 788/1015 [00:03<00:00, 237.46it/s]

tensor([[0.6411, 0.3589]], device='cuda:0')
tensor([[0.4361, 0.5639]], device='cuda:0')
tensor([[0.5794, 0.4206]], device='cuda:0')
tensor([[0.5411, 0.4589]], device='cuda:0')
tensor([[0.5043, 0.4957]], device='cuda:0')
tensor([[0.5442, 0.4558]], device='cuda:0')
tensor([[0.6258, 0.3742]], device='cuda:0')
tensor([[0.6333, 0.3667]], device='cuda:0')
tensor([[0.6073, 0.3927]], device='cuda:0')
tensor([[0.5360, 0.4640]], device='cuda:0')
tensor([[0.5507, 0.4493]], device='cuda:0')
tensor([[0.5396, 0.4604]], device='cuda:0')
tensor([[0.4811, 0.5189]], device='cuda:0')
tensor([[0.5601, 0.4399]], device='cuda:0')
tensor([[0.5154, 0.4846]], device='cuda:0')
tensor([[0.5318, 0.4682]], device='cuda:0')
tensor([[0.5680, 0.4320]], device='cuda:0')
tensor([[0.6177, 0.3823]], device='cuda:0')
tensor([[0.6615, 0.3385]], device='cuda:0')
tensor([[0.5400, 0.4600]], device='cuda:0')
tensor([[0.6289, 0.3711]], device='cuda:0')
tensor([[0.4872, 0.5128]], device='cuda:0')
tensor([[0.4623, 0.5377]], devic

 83%|████████▎ | 839/1015 [00:03<00:00, 227.50it/s]

tensor([[0.4925, 0.5075]], device='cuda:0')
tensor([[0.5739, 0.4261]], device='cuda:0')
tensor([[0.5183, 0.4817]], device='cuda:0')
tensor([[0.5301, 0.4699]], device='cuda:0')
tensor([[0.5889, 0.4111]], device='cuda:0')
tensor([[0.5430, 0.4570]], device='cuda:0')
tensor([[0.5699, 0.4301]], device='cuda:0')
tensor([[0.4967, 0.5033]], device='cuda:0')
tensor([[0.5224, 0.4776]], device='cuda:0')
tensor([[0.5275, 0.4725]], device='cuda:0')
tensor([[0.4746, 0.5254]], device='cuda:0')
tensor([[0.6054, 0.3946]], device='cuda:0')
tensor([[0.5564, 0.4436]], device='cuda:0')
tensor([[0.5481, 0.4519]], device='cuda:0')
tensor([[0.4284, 0.5716]], device='cuda:0')
tensor([[0.5359, 0.4641]], device='cuda:0')
tensor([[0.5508, 0.4492]], device='cuda:0')
tensor([[0.5291, 0.4709]], device='cuda:0')
tensor([[0.4543, 0.5457]], device='cuda:0')
tensor([[0.4661, 0.5339]], device='cuda:0')
tensor([[0.5279, 0.4721]], device='cuda:0')
tensor([[0.5994, 0.4006]], device='cuda:0')
tensor([[0.6978, 0.3022]], devic

 85%|████████▌ | 863/1015 [00:03<00:00, 230.08it/s]

tensor([[0.5628, 0.4372]], device='cuda:0')
tensor([[0.5075, 0.4925]], device='cuda:0')
tensor([[0.5107, 0.4893]], device='cuda:0')
tensor([[0.4538, 0.5462]], device='cuda:0')
tensor([[0.5223, 0.4777]], device='cuda:0')
tensor([[0.4895, 0.5105]], device='cuda:0')
tensor([[0.5931, 0.4069]], device='cuda:0')
tensor([[0.5509, 0.4491]], device='cuda:0')
tensor([[0.4962, 0.5038]], device='cuda:0')
tensor([[0.5639, 0.4361]], device='cuda:0')
tensor([[0.4797, 0.5203]], device='cuda:0')
tensor([[0.5542, 0.4458]], device='cuda:0')
tensor([[0.5630, 0.4370]], device='cuda:0')
tensor([[0.5590, 0.4410]], device='cuda:0')
tensor([[0.4953, 0.5047]], device='cuda:0')
tensor([[0.4917, 0.5083]], device='cuda:0')
tensor([[0.5494, 0.4506]], device='cuda:0')
tensor([[0.5621, 0.4379]], device='cuda:0')
tensor([[0.4612, 0.5388]], device='cuda:0')
tensor([[0.5174, 0.4826]], device='cuda:0')
tensor([[0.5556, 0.4444]], device='cuda:0')
tensor([[0.5055, 0.4945]], device='cuda:0')
tensor([[0.5208, 0.4792]], devic

 90%|████████▉ | 913/1015 [00:03<00:00, 201.77it/s]

tensor([[0.5033, 0.4967]], device='cuda:0')
tensor([[0.6485, 0.3515]], device='cuda:0')
tensor([[0.5644, 0.4356]], device='cuda:0')
tensor([[0.5728, 0.4272]], device='cuda:0')
tensor([[0.5385, 0.4615]], device='cuda:0')
tensor([[0.5508, 0.4492]], device='cuda:0')
tensor([[0.5586, 0.4414]], device='cuda:0')
tensor([[0.5462, 0.4538]], device='cuda:0')
tensor([[0.4442, 0.5558]], device='cuda:0')
tensor([[0.5352, 0.4648]], device='cuda:0')
tensor([[0.4626, 0.5374]], device='cuda:0')
tensor([[0.5167, 0.4833]], device='cuda:0')
tensor([[0.5368, 0.4632]], device='cuda:0')
tensor([[0.5338, 0.4662]], device='cuda:0')
tensor([[0.4481, 0.5519]], device='cuda:0')
tensor([[0.4879, 0.5121]], device='cuda:0')
tensor([[0.5129, 0.4871]], device='cuda:0')
tensor([[0.5943, 0.4057]], device='cuda:0')
tensor([[0.5762, 0.4238]], device='cuda:0')
tensor([[0.5365, 0.4635]], device='cuda:0')
tensor([[0.5290, 0.4710]], device='cuda:0')
tensor([[0.5658, 0.4342]], device='cuda:0')
tensor([[0.4628, 0.5372]], devic

 96%|█████████▋| 977/1015 [00:04<00:00, 250.63it/s]

tensor([[0.5817, 0.4183]], device='cuda:0')
tensor([[0.6385, 0.3615]], device='cuda:0')
tensor([[0.5058, 0.4942]], device='cuda:0')
tensor([[0.5265, 0.4735]], device='cuda:0')
tensor([[0.5095, 0.4905]], device='cuda:0')
tensor([[0.4802, 0.5198]], device='cuda:0')
tensor([[0.5395, 0.4605]], device='cuda:0')
tensor([[0.5423, 0.4577]], device='cuda:0')
tensor([[0.5597, 0.4403]], device='cuda:0')
tensor([[0.6578, 0.3422]], device='cuda:0')
tensor([[0.5221, 0.4779]], device='cuda:0')
tensor([[0.4975, 0.5025]], device='cuda:0')
tensor([[0.5593, 0.4407]], device='cuda:0')
tensor([[0.6712, 0.3288]], device='cuda:0')
tensor([[0.4678, 0.5322]], device='cuda:0')
tensor([[0.5610, 0.4390]], device='cuda:0')
tensor([[0.5608, 0.4392]], device='cuda:0')
tensor([[0.4882, 0.5118]], device='cuda:0')
tensor([[0.4384, 0.5616]], device='cuda:0')
tensor([[0.4714, 0.5286]], device='cuda:0')
tensor([[0.5847, 0.4153]], device='cuda:0')
tensor([[0.4710, 0.5290]], device='cuda:0')
tensor([[0.5330, 0.4670]], devic

100%|██████████| 1015/1015 [00:04<00:00, 241.43it/s]

tensor([[0.4963, 0.5037]], device='cuda:0')
tensor([[0.5891, 0.4109]], device='cuda:0')
tensor([[0.5564, 0.4436]], device='cuda:0')
tensor([[0.4954, 0.5046]], device='cuda:0')
tensor([[0.6130, 0.3870]], device='cuda:0')
tensor([[0.5172, 0.4828]], device='cuda:0')
tensor([[0.5637, 0.4363]], device='cuda:0')
tensor([[0.5652, 0.4348]], device='cuda:0')
SVC Accuracy: 0.54
GNB Accuracy: 0.53
NN Accuracy: 0.55
Voting Accuracy: 0.54
Predicted winner is Red Team
SVC model predicted Red Team
GNB model predicted Red Team
NN model predicted Blue Team with a 58.67% chance
Found no games with 5 or more similar characters
